baseurl = "https://harlecin.netlify.com/"
title = "semper quaerere"
author = "Christoph Bodner"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsstyle       = "bw"
pygmentscodefences  = true

paginate = 5
paginatePath  = "posts"

[params]
  sitename = "semper quaerere"
  
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    url  = "/projects/project_1"
[[menu.main]]
    name = "Resume"
    url  = "/projects/project_1"

